### ISSUE TITLE
Weather Auto render

### ISSUE THREAD

**Issue by ipax77** [danroth27/Net8BlazorAuto#3]
When trying to implement the Weather Page as Auto rendered [GitHub](https://github.com/ipax77/Net8BlazorAuto/tree/weatherforecast) the data is being loaded on the server every time. Is it possible to get rid of the initial Server load? Or where can I change the RenderMode.ServerPrerendered for the Server?

First load:
```
info: Net8BlazorAuto.Services.WeatherService[0]
      getting weather from Server - 2023-08-10 07:39:59
info: Net8BlazorAuto.Services.WeatherService[0]
      getting weather from Client - 2023-08-10 07:40:04
```

Second load:
```
info: Net8BlazorAuto.Services.WeatherService[0]
      getting weather from Server - 2023-08-10 07:46:49
info: Net8BlazorAuto.Services.WeatherService[0]
      getting weather from Client - 2023-08-10 07:46:50
```

First load with slow 3G Network:
```
info: Net8BlazorAuto.Services.WeatherService[0]
      getting weather from Server - 2023-08-10 07:42:16
info: Net8BlazorAuto.Services.WeatherService[0]
      getting weather from Server - 2023-08-10 07:42:24
```

**Comment by danroth27** [comment]
Hi @ipax77. The weather data will get loaded on the server as part of prerendering the page. If you want to turn off prerendering you can do that by setting the render mode to `@rendermode="@(new ServerRenderMode(prerender: false))"`. We are also working to [enable persisting the prerendered state](https://github.com/dotnet/aspnetcore/pull/50625) so that it can be reused on the client.
